import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";
import { sveltePreprocess } from "svelte-preprocess";

const dirname = path.dirname(fileURLToPath(import.meta.url));

function gitWorkerSourcePlugin() {
    return {
        name: "git-worker-source",
        setup(build) {
            build.onLoad({ filter: /gitWorkerSource\.ts$/ }, async () => {
                const result = await esbuild.build({
                    absWorkingDir: dirname,
                    entryPoints: ["src/gitManager/wasmGit/gitWorker.ts"],
                    bundle: true,
                    write: false,
                    format: "iife",
                    platform: "browser",
                    target: "es2018",
                    logLevel: "silent",
                    external: [
                        "node:module",
                        "node:crypto",
                        "node:fs",
                        "node:url",
                        "node:path",
                        "ws",
                        "worker_threads",
                    ],
                    plugins: [
                        {
                            name: "stub-wasm-in-worker",
                            setup(workerBuild) {
                                workerBuild.onLoad(
                                    { filter: /\.wasm$/ },
                                    () => ({
                                        contents:
                                            "export default new Uint8Array();",
                                        loader: "js",
                                    })
                                );
                            },
                        },
                    ],
                });
                const code = result.outputFiles?.[0]?.text ?? "";
                return {
                    contents: `export const GIT_WORKER_SOURCE = ${JSON.stringify(code)};`,
                    loader: "js",
                };
            });
        },
    };
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository (https://github.com/denolehov/obsidian-git)
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "child_process",
        "fs",
        "os",
        "path",
        "moment",
        "node:events",
        "node:path",
        "node:util",
        // Referenced by wasm-git's Emscripten glue behind Node-environment
        // guards that never trigger inside Obsidian.
        "node:crypto",
        "node:fs",
        "node:module",
        "node:url",
        "ws",
        "worker_threads",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    // The wasm-git engine (libgit2 compiled to WebAssembly) is embedded into
    // main.js as raw bytes and instantiated manually at runtime.
    loader: {
        ".wasm": "binary",
    },
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    platform: "browser",
    minify: prod,
    conditions: [prod ? "production" : "development"], // https://www.npmjs.com/package/esm-env
    plugins: [
        gitWorkerSourcePlugin(),
        esbuildSvelte({
            compilerOptions: {
                css: "injected",
                dev: !prod,
            },
            filterWarnings: (warning) => {
                if (warning.code.startsWith("a11y-")) return false;
                return true;
            },
            preprocess: sveltePreprocess(),
        }),
    ],
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
