allowBuilds:
  '@parcel/watcher': false
  classic-level: true
  edgedriver: false
  esbuild: true
  geckodriver: false
  svelte-preprocess: true
  tldjs: false
minimumReleaseAgeExclude:
  - rulesync@16.17.0
